/// The status of a verification session.
enum SessionStatus {
  created,
  active,
  verified,
  expired,
  ended
}

/// Represents a caller-verification session.
class VerificationSession {
  final String sessionId;
  final String code;
  final DateTime expiresAt;
  final SessionStatus status;

  VerificationSession({
    required this.sessionId,
    required this.code,
    required this.expiresAt,
    required this.status,
  });

  /// Creates a session from a JSON map.
  factory VerificationSession.fromJson(Map<String, dynamic> json) {
    return VerificationSession(
      sessionId: json['session_id'] as String,
      code: json['code'] as String,
      expiresAt: DateTime.parse(json['expires_at'] as String),
      status: _parseStatus(json['status'] as String),
    );
  }

  /// Converts the session to a JSON map.
  Map<String, dynamic> toJson() {
    return {
      'session_id': sessionId,
      'code': code,
      'expires_at': expiresAt.toIso8601String(),
      'status': status.name,
    };
  }

  static SessionStatus _parseStatus(String statusStr) {
    switch (statusStr) {
      case 'created': return SessionStatus.created;
      case 'active': return SessionStatus.active;
      case 'verified': return SessionStatus.verified;
      case 'expired': return SessionStatus.expired;
      case 'ended': return SessionStatus.ended;
      default: return SessionStatus.ended;
    }
  }
}

/// An error returned by the Ringseal API or generated by the SDK.
class RingsealError implements Exception {
  final String code;
  final String message;

  RingsealError({
    required this.code,
    required this.message,
  });

  /// Creates an error from a JSON map.
  factory RingsealError.fromJson(Map<String, dynamic> json) {
    return RingsealError(
      code: json['code'] as String? ?? 'unknown',
      message: json['message'] as String? ?? 'An unknown error occurred.',
    );
  }

  @override
  String toString() => 'RingsealError($code): $message';
}
